//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmNo { get; set; }
        public string Ad { get; set; }
        public string Tur { get; set; }
        public Nullable<int> Sure { get; set; }
        public Nullable<decimal> Ucret { get; set; }
        public Nullable<int> Puan { get; set; }
        public Nullable<System.DateTime> VizyonTarihi { get; set; }
        public Nullable<int> SNo { get; set; }
    }
}
