//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASinemaEntities6 : DbContext
    {
        public ASinemaEntities6()
            : base("name=ASinemaEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Film> Films { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
        public virtual DbSet<Sube> Subes { get; set; }
    
        public virtual ObjectResult<FAra_Result> FAra(string ad)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FAra_Result>("FAra", adParameter);
        }
    
        public virtual int FEkle(string ad, string tur, Nullable<int> sure, Nullable<decimal> ucret, Nullable<int> puan, Nullable<System.DateTime> vizyonTarihi)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var turParameter = tur != null ?
                new ObjectParameter("Tur", tur) :
                new ObjectParameter("Tur", typeof(string));
    
            var sureParameter = sure.HasValue ?
                new ObjectParameter("Sure", sure) :
                new ObjectParameter("Sure", typeof(int));
    
            var ucretParameter = ucret.HasValue ?
                new ObjectParameter("Ucret", ucret) :
                new ObjectParameter("Ucret", typeof(decimal));
    
            var puanParameter = puan.HasValue ?
                new ObjectParameter("Puan", puan) :
                new ObjectParameter("Puan", typeof(int));
    
            var vizyonTarihiParameter = vizyonTarihi.HasValue ?
                new ObjectParameter("VizyonTarihi", vizyonTarihi) :
                new ObjectParameter("VizyonTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FEkle", adParameter, turParameter, sureParameter, ucretParameter, puanParameter, vizyonTarihiParameter);
        }
    
        public virtual ObjectResult<FListele_Result> FListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FListele_Result>("FListele");
        }
    
        public virtual int FSil(Nullable<int> filmNo)
        {
            var filmNoParameter = filmNo.HasValue ?
                new ObjectParameter("FilmNo", filmNo) :
                new ObjectParameter("FilmNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FSil", filmNoParameter);
        }
    
        public virtual int FYenile(Nullable<int> filmNo, string ad, string tur, Nullable<int> sure, Nullable<decimal> ucret, Nullable<int> puan, Nullable<System.DateTime> vizyonTarihi)
        {
            var filmNoParameter = filmNo.HasValue ?
                new ObjectParameter("FilmNo", filmNo) :
                new ObjectParameter("FilmNo", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var turParameter = tur != null ?
                new ObjectParameter("Tur", tur) :
                new ObjectParameter("Tur", typeof(string));
    
            var sureParameter = sure.HasValue ?
                new ObjectParameter("Sure", sure) :
                new ObjectParameter("Sure", typeof(int));
    
            var ucretParameter = ucret.HasValue ?
                new ObjectParameter("Ucret", ucret) :
                new ObjectParameter("Ucret", typeof(decimal));
    
            var puanParameter = puan.HasValue ?
                new ObjectParameter("Puan", puan) :
                new ObjectParameter("Puan", typeof(int));
    
            var vizyonTarihiParameter = vizyonTarihi.HasValue ?
                new ObjectParameter("VizyonTarihi", vizyonTarihi) :
                new ObjectParameter("VizyonTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FYenile", filmNoParameter, adParameter, turParameter, sureParameter, ucretParameter, puanParameter, vizyonTarihiParameter);
        }
    
        public virtual ObjectResult<Giris_Result> Giris(string kadi, string sifre)
        {
            var kadiParameter = kadi != null ?
                new ObjectParameter("kadi", kadi) :
                new ObjectParameter("kadi", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("sifre", sifre) :
                new ObjectParameter("sifre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Giris_Result>("Giris", kadiParameter, sifreParameter);
        }
    
        public virtual int KEkle(string kullaniciAd, string sifre, string adSoyad, string gorev, Nullable<int> subeNo)
        {
            var kullaniciAdParameter = kullaniciAd != null ?
                new ObjectParameter("KullaniciAd", kullaniciAd) :
                new ObjectParameter("KullaniciAd", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("Sifre", sifre) :
                new ObjectParameter("Sifre", typeof(string));
    
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var gorevParameter = gorev != null ?
                new ObjectParameter("Gorev", gorev) :
                new ObjectParameter("Gorev", typeof(string));
    
            var subeNoParameter = subeNo.HasValue ?
                new ObjectParameter("SubeNo", subeNo) :
                new ObjectParameter("SubeNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KEkle", kullaniciAdParameter, sifreParameter, adSoyadParameter, gorevParameter, subeNoParameter);
        }
    
        public virtual ObjectResult<SAra_Result> SAra(string salonAd)
        {
            var salonAdParameter = salonAd != null ?
                new ObjectParameter("SalonAd", salonAd) :
                new ObjectParameter("SalonAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAra_Result>("SAra", salonAdParameter);
        }
    
        public virtual int SEkle(string salonAd, Nullable<int> koltukSayisi)
        {
            var salonAdParameter = salonAd != null ?
                new ObjectParameter("SalonAd", salonAd) :
                new ObjectParameter("SalonAd", typeof(string));
    
            var koltukSayisiParameter = koltukSayisi.HasValue ?
                new ObjectParameter("KoltukSayisi", koltukSayisi) :
                new ObjectParameter("KoltukSayisi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SEkle", salonAdParameter, koltukSayisiParameter);
        }
    
        public virtual ObjectResult<SListele_Result> SListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SListele_Result>("SListele");
        }
    
        public virtual int SSil(Nullable<int> salonNo)
        {
            var salonNoParameter = salonNo.HasValue ?
                new ObjectParameter("SalonNo", salonNo) :
                new ObjectParameter("SalonNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SSil", salonNoParameter);
        }
    
        public virtual int SYenile(Nullable<int> salonNo, string salonAd, Nullable<int> koltukSayisi)
        {
            var salonNoParameter = salonNo.HasValue ?
                new ObjectParameter("SalonNo", salonNo) :
                new ObjectParameter("SalonNo", typeof(int));
    
            var salonAdParameter = salonAd != null ?
                new ObjectParameter("SalonAd", salonAd) :
                new ObjectParameter("SalonAd", typeof(string));
    
            var koltukSayisiParameter = koltukSayisi.HasValue ?
                new ObjectParameter("KoltukSayisi", koltukSayisi) :
                new ObjectParameter("KoltukSayisi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SYenile", salonNoParameter, salonAdParameter, koltukSayisiParameter);
        }
    
        public virtual ObjectResult<KAra_Result> KAra(string kullaniciAd)
        {
            var kullaniciAdParameter = kullaniciAd != null ?
                new ObjectParameter("KullaniciAd", kullaniciAd) :
                new ObjectParameter("KullaniciAd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KAra_Result>("KAra", kullaniciAdParameter);
        }
    
        public virtual ObjectResult<KListele_Result> KListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KListele_Result>("KListele");
        }
    
        public virtual int KSil(Nullable<int> kullaniciNo)
        {
            var kullaniciNoParameter = kullaniciNo.HasValue ?
                new ObjectParameter("KullaniciNo", kullaniciNo) :
                new ObjectParameter("KullaniciNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KSil", kullaniciNoParameter);
        }
    
        public virtual int KYenile(Nullable<int> kullaniciNo, string kullaniciAd, string sifre, string adSoyad, string gorev, Nullable<int> subeNo)
        {
            var kullaniciNoParameter = kullaniciNo.HasValue ?
                new ObjectParameter("KullaniciNo", kullaniciNo) :
                new ObjectParameter("KullaniciNo", typeof(int));
    
            var kullaniciAdParameter = kullaniciAd != null ?
                new ObjectParameter("KullaniciAd", kullaniciAd) :
                new ObjectParameter("KullaniciAd", typeof(string));
    
            var sifreParameter = sifre != null ?
                new ObjectParameter("Sifre", sifre) :
                new ObjectParameter("Sifre", typeof(string));
    
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var gorevParameter = gorev != null ?
                new ObjectParameter("Gorev", gorev) :
                new ObjectParameter("Gorev", typeof(string));
    
            var subeNoParameter = subeNo.HasValue ?
                new ObjectParameter("SubeNo", subeNo) :
                new ObjectParameter("SubeNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KYenile", kullaniciNoParameter, kullaniciAdParameter, sifreParameter, adSoyadParameter, gorevParameter, subeNoParameter);
        }
    
        public virtual ObjectResult<SubeAra_Result> SubeAra(string ad)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubeAra_Result>("SubeAra", adParameter);
        }
    
        public virtual int SubeEkle(string ad, Nullable<int> salonSayisi, Nullable<int> calisanSayisi)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var salonSayisiParameter = salonSayisi.HasValue ?
                new ObjectParameter("SalonSayisi", salonSayisi) :
                new ObjectParameter("SalonSayisi", typeof(int));
    
            var calisanSayisiParameter = calisanSayisi.HasValue ?
                new ObjectParameter("CalisanSayisi", calisanSayisi) :
                new ObjectParameter("CalisanSayisi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubeEkle", adParameter, salonSayisiParameter, calisanSayisiParameter);
        }
    
        public virtual ObjectResult<SubeListele_Result> SubeListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubeListele_Result>("SubeListele");
        }
    
        public virtual int SubeSil(Nullable<int> subeNo)
        {
            var subeNoParameter = subeNo.HasValue ?
                new ObjectParameter("SubeNo", subeNo) :
                new ObjectParameter("SubeNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubeSil", subeNoParameter);
        }
    
        public virtual int SubeYenile(Nullable<int> subeNo, string ad, Nullable<int> salonSayisi, Nullable<int> calisanSayisi)
        {
            var subeNoParameter = subeNo.HasValue ?
                new ObjectParameter("SubeNo", subeNo) :
                new ObjectParameter("SubeNo", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var salonSayisiParameter = salonSayisi.HasValue ?
                new ObjectParameter("SalonSayisi", salonSayisi) :
                new ObjectParameter("SalonSayisi", typeof(int));
    
            var calisanSayisiParameter = calisanSayisi.HasValue ?
                new ObjectParameter("CalisanSayisi", calisanSayisi) :
                new ObjectParameter("CalisanSayisi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SubeYenile", subeNoParameter, adParameter, salonSayisiParameter, calisanSayisiParameter);
        }
    }
}
